const fs = require('fs');

const text = `municipio,punto de votacion,mesas
AGUA DE DIOS,IED SALESIANO MIGUEL UNIA,20
AGUA DE DIOS,CEN. CULTURAL ARMANDO RODRIGUEZ JIMENEZ,10
ALBAN,PUESTO CABECERA MUNICIPAL,16
ALBAN,COLEGIO CHIMBE,1
ANAPOIMA,POLIDEPORTIVO JULIO CESAR SANCHEZ,23
ANAPOIMA,CASA DE LA CULTURA,10
ANAPOIMA,LA PAZ,4
ANAPOIMA,SAN ANTONIO,4
ANOLAIMA,PUESTO CABECERA MUNICIPAL,29
ANOLAIMA,LA FLORIDA,5
ANOLAIMA,CORRALEJAS,1
ANOLAIMA,REVENTONES,3
ARBELAEZ,CTRO COLISEO RAFAEL DIONISIO PARRA REYES,29
ARBELAEZ,IE DEPARTAMENTAL JOHN F. KENNEDY,2
BELTRAN,PUESTO CABECERA MUNICIPAL,3
BELTRAN,PAQUILO,3
BELTRAN,PUERTO DE GRAMALOTAL,1
BITUIMA,PUESTO CABECERA MUNICIPAL,9
BITUIMA,LA PLAZUELA,1
BITUIMA,BOQUERON DE ILO (VDA RINCON SANTO),1
BOJACA,PUESTO CABECERA MUNICIPAL,23
CABRERA,PUESTO CABECERA MUNICIPAL,11
CABRERA,SALON COMUNAL,1
CACHIPAY,PUESTO CABECERA MUNICIPAL,27
CACHIPAY,PEÑA NEGRA,4
CAJICA,ESCUELA EL MISTERIO,18
CAJICA,COLEGIO RINCON SANTO,20
CAJICA,COLEGIO PABLO HERRERA,22
CAJICA,I.E.D CAPELLANIA,9
CAJICA,COLISEO FORTALEZA DE PIEDRA,19
CAJICA,CENTRO CULTURAL CAJICA,27
CAJICA,COLEGIO ANTONIO NARIÑO,25
CAJICA,SALON COMUNAL LAS PALMAS,15
CAJICA,SALON COMUNAL BARRIO GRANJITAS,6
CAJICA,IED POMPILIO MARTINEZ,17
CAJICA,CLUB EDAD DE ORO,20
CAJICA,IE DEPARTAMENTAL SAN GABRIEL,3
CAPARRAPI,PUESTO CABECERA MUNICIPAL,20
CAPARRAPI,CAMBRAS,1
CAPARRAPI,CANCHIMAY,1
CAPARRAPI,CACERES,1
CAPARRAPI,CORDOBA,1
CAPARRAPI,EL CAMBULO,2
CAPARRAPI,EL DINDAL,2
CAPARRAPI,LA AZAUNCHA,1
CAPARRAPI,SAN CARLOS,3
CAPARRAPI,SAN PEDRO,3
CAPARRAPI,TATI,1
CAPARRAPI,SAN RAMON ALTO,1
CAQUEZA,COLISEO GERMAN ROJAS URREGO,29
CAQUEZA,CONCENTRACION MARILANDA,17
CAQUEZA,CARCEL,1
CAQUEZA,SALON COMUNAL GIRON DE BLANCOS,1
CARMEN DE CARUPA,PUESTO CABECERA MUNICIPAL,18
CARMEN DE CARUPA,HATO,2
CARMEN DE CARUPA,SUCRE (CAPILLA DE SUCRE),1
COGUA,COLEGIO LAS VILLAS,33
COGUA,POLIDEPORTIVO MUNICIPAL,18
COGUA,VEREDA LA PLAZUELA,1
COTA,IED ENRIQUE PARDO PARRA SD BACHILLERATO,26
COTA,IE DEPARTAMENTAL CAMILO TORRES,27
COTA,IE DEPARTAMENTAL PARCELAS,10
COTA,I.E.PUEBLO VIEJO,18
COTA,I.E LA MOYA,15
CUCUNUBA,POLIDEPORTIVO MUNICIPAL,12
CUCUNUBA,CENTRO  INTERACTIVO CULTURAL CILAB,3
CUCUNUBA,PEÑAS (LA PLUMA),2
CHAGUANI,PUESTO CABECERA MUNICIPAL,13
CHIA,INST. EDUC. DIVERSIFICADA SANTA LUCIA,28
CHIA,COLEGIO NACIONAL DIVERSIFICADO,33
CHIA,COLEGIO STELLA MATUTINA,20
CHIA,COLEGIO MARIA AUXILIADORA,21
CHIA,VEREDA LA BALSA,8
CHIA,INSTITUCION EDUCATIVA CERCA DE PIEDRA,7
CHIA,INSTITUCION EDUCATIVA FONQUETA,4
CHIA,IE JOSE ESCRIVA DE BALAGUER SEDE SAMARIA,6
CHIA,COLISEO DE LA LUNA,28
CHIA,IE JOSE ESCRIVA BALAGUER,24
CHIA,UNIVERSIDAD DE CUNDINAMARCA,28
CHIA,IE EL CERRO,6
CHIA,CONCHA ACUSTICA,33
CHIA,INST. EDUCATIVA FAGUA SECTOR TIQUIZA,10
CHIA,CENTRO COMERCIAL FONTANAR,25
CHIA,INSTITUCION EDUCATIVA DIOSA CHIA,5
CHIA,COLEGIO JOSE JOAQUIN CASAS,12
CHIA,COLEGIO CELESTIN FREINET,13
CHIA,CENTRO  COMERCIAL CENTRO CHIA,9
CHIA,CENTRO CULTURAL Y ARTISTICO JUMBO,8
CHIA,UNIDAD DEPORTIVA LA LORENA,2
CHIA,UNIDAD DEPORTIVA FAGUA,2
CHIA,INST.EDUC.LAURA VICUÑA,28
CHIPAQUE,PUESTO CABECERA MUNICIPAL,26
CHOACHI,IED IGNACIO PESCADOR,30
CHOACHI,COLISEO POLIDEPORTIVO EL BOSQUE,5
CHOACHI,EL ALTO DEL PALO,2
CHOACHI,POTRERO GRANDE,1
CHOCONTA,IED AGROINDUSTRIAL SANTIAGO DE CHOCONTA,34
CHOCONTA,IED RUFINO CUERVO,18
CHOCONTA,CARCEL,1
EL COLEGIO,ESC. URB. FRANCISCO JULIAN OLAYA,28
EL COLEGIO,VILLA OLIMPICA,23
EL COLEGIO,JARDIN INFANTIL DEPTAL CARLOS JIMENEZ G.,6
EL COLEGIO,EL TRIUNFO,5
EL COLEGIO,IED LA VICTORIA,7
EL COLEGIO,INSPECCION PRADILLA SALON COMUNAL,4
EL PEÑON,PUESTO CABECERA MUNICIPAL,10
EL PEÑON,GUAYABAL DE TOLEDO,2
EL PEÑON,TALAUTA,3
EL ROSAL,COLISEO MUNICIPAL,28
EL ROSAL,IED CAMPO ALEGRE,3
EL ROSAL,MEGA COLEGIO,29
EL ROSAL,ESCUELA RURAL LA PIÑUELA,1
FACATATIVA,COLEGIO DEPTAL CARTAGENITA,23
FACATATIVA,COLEGIO MANABLANCA,9
FACATATIVA,COLEGIO JOHN F. KENNEDY,25
FACATATIVA,CENTRO DE DESARROLLO SOCIAL,17
FACATATIVA,COLEGIO SAN AGUSTIN,16
FACATATIVA,COLEGIO SILVERIA ESPINOSA,19
FACATATIVA,EL PORTAL DE TUS SUEÑOS,11
FACATATIVA,ESC. PRIM. SD SAN CRIST. JOHN F KENNEDY,3
FACATATIVA,COLEGIO SD MOLINOS - MANUELA AYALA,2
FACATATIVA,COL. CARTAGENITA BLOQUE D SEDE PRIMARIA,5
FACATATIVA,CTRO DE DISCAPACIDAD MANUEL GONZALEZ C.,1
FACATATIVA,INSTITUTO  TECNICO  INDUSTRIAL,25
FACATATIVA,ESCUELA RAFAEL POMBO,21
FACATATIVA,COLEGIO MANUELA AYALA DE GAITAN,27
FACATATIVA,COLEGIO SANTA RITA,26
FACATATIVA,COLEGIO NACIONAL EMILIO CIFUENTES,27
FACATATIVA,INDUSTRIAL SEDE TALLERES,20
FACATATIVA,CTRO EDU LA CONCEPCION,9
FACATATIVA,UNIVERSIDAD CUNDINAMARCA,8
FACATATIVA,COLEGIO ARBOLEDA SEDE ARBOLEDA,6
FACATATIVA,COLEGIO ARBOLEDA S  JUAN PABLO II,21
FACATATIVA,CTRO RECLUSION POLICIA NAL,1
FACATATIVA,COLEGIO JUAN XXIII,2
FACATATIVA,ESCUELA ANTIGUA MANCILLA,1
FOMEQUE,IED MONSEÑOR AGUSTIN GUTIERREZ,24
FOMEQUE,POLIDEPORTIVO MUNICIPAL,5
FOMEQUE,LA UNION,2
FOMEQUE,SAN LORENZO,1
FOSCA,PUESTO CABECERA MUNICIPAL,14
FOSCA,PUEBLO VIEJO,1
FOSCA,SANAME,3
FUNZA,COL MIL CNEL JUAN JOSE RONDON,27
FUNZA,COL TEC IND CORAZON DE MARIA,11
FUNZA,IED JARDIN SOCIAL SERREZUELITA,8
FUNZA,COL MIGUEL ANTONIO CARO,24
FUNZA,COL FURATENA,12
FUNZA,COLISEO MUNICIPAL,15
FUNZA,I E SERREZUELITA,7
FUNZA,I E EL HATO,4
FUNZA,IE DEPARTAMENTAL DE FUNZA,2
FUNZA,COL SAN JOSE,17
FUNZA,COL NUESTRA SEÑORA DEL ROSARIO,10
FUNZA,COL SANTANA,7
FUNZA,COL PARROQUIAL SANTIAGO APOSTOL,5
FUNZA,COL CRISTIANO INTEGRAL,13
FUNZA,ESC SAN ANDRES,8
FUNZA,COL COOPERATIVO COMUNAL,22
FUNZA,COL LA UNIDAD BASICA,19
FUNZA,I E SAN MARCOS,3
FUNZA,COL BICENTENARIO,21
FUNZA,JARDIN INFANTIL VILLA PAUL,3
FUNZA,JARDIN INFANTIL LA AURORA,2
FUNZA,IE MARIA INMACULADA,9
FUNZA,CARCEL MUNICIPAL FUNZA,1
FUQUENE,PUESTO CABECERA MUNICIPAL,6
FUQUENE,CAPELLANIA,6
FUQUENE,NUEVO FUQUENE,1
FUSAGASUGA,ESCUELA JULIO SABOGAL,16
FUSAGASUGA,COLEGIO ACCION COMUNAL,20
FUSAGASUGA,COLEGIO MANUEL HUMBERTO CARDENAS VELEZ,4
FUSAGASUGA,ESCUELA MANUELA BELTRAN,2
FUSAGASUGA,CTRO DE INNOVACION E INTEGRACION SOCIAL,7
FUSAGASUGA,COLISEO FUTSAL COBURGO,24
FUSAGASUGA,ESCUELA GUSTAVO VEGA,15
FUSAGASUGA,ESCUELA CAMILO TORRES,5
FUSAGASUGA,ESCUELA GENERAL SANTANDER,2
FUSAGASUGA,PARROQUIA NTRA.SRA.DE BELEN,14
FUSAGASUGA,FUND.DE EDUC.EN SALUD MARIE POUSSEPIN,20
FUSAGASUGA,CENTRO DE DESARROLLO INFANTIL,7
FUSAGASUGA,ESCUELA FUSACATAN,13
FUSAGASUGA,COL CARLOS LOZANO Y LOZANO,21
FUSAGASUGA,COL JOSE C MUTIS,14
FUSAGASUGA,ESC. SUPERIOR DE ADMON PUBLICA-ESAP,10
FUSAGASUGA,COL. JOSE CELESTINO MUTIS SD LUSITANIA,11
FUSAGASUGA,UNIVERSIDAD DE CUNDINAMARCA,25
FUSAGASUGA,COLEGIO RICAURTE,25
FUSAGASUGA,UNIVERSIDAD ABIERTA Y A DISTANCIA UNAD,3
FUSAGASUGA,CENTRO ACADEMICO DEPORTIVO CERCUN,3
FUSAGASUGA,ESC REFUGIO INFANTIL,17
FUSAGASUGA,POLIDEPORTIVO EBENEZER,10
FUSAGASUGA,CENTRO DE INTEGRACION CIUDADANA,6
FUSAGASUGA,IEM CIUDAD EBEN-EZER,12
FUSAGASUGA,POLIDEPORTIVO LLANO LARGO,3
FUSAGASUGA,COL.TEODORO AYA VILLAVECES,12
FUSAGASUGA,CARCEL CIRCUITO JUDICIAL,1
FUSAGASUGA,LA AGUADITA,6
FUSAGASUGA,LOS SAUCES,5
FUSAGASUGA,CUCHARAL,12
FUSAGASUGA,COLEGIO AGRICOLA VALSALICE,1
FUSAGASUGA,BOCHICA (LA TRINIDAD),9
FUSAGASUGA,COLEGIO ESPINALITO ALTO,2
FUSAGASUGA,EL TRIUNFO (BOQUERON),3
FUSAGASUGA,LA PUERTA (CHINAUTA),12
GACHALA,PUESTO CABECERA MUNICIPAL,13
GACHALA,INSPECCION LOS ALPES,3
GACHALA,CORREGIMIENTO  MONTECRISTO,1
GACHALA,CORREGIMIENTO  SANTA RITA DE RIONEGRO,1
GACHALA,VEREDA MURCA,1
GACHANCIPA,COL. CARLOS GARAVITO - SEDE CIUDADELA,32
GACHANCIPA,AULA MULTIPLE COLEGIO SEDE CIUDADELA,6
GACHETA,CAMPO DEPORTIVO LA COLOMBIA,17
GACHETA,ESCUELA JHON F KENNEDY,10
GACHETA,CARCEL,1
GACHETA,LOS LOPEZ,1
GAMA,PUESTO CABECERA MUNICIPAL,9
GAMA,SAN ROQUE,1
GIRARDOT,COLEGIO AMERICANO,24
GIRARDOT,COLEGIO LA PRESENTACION,18
GIRARDOT,COLEGIO NUESTRA SEÑORA DEL PILAR,15
GIRARDOT,CASA DE LA CULTURA,3
GIRARDOT,IE FUNDADORES RAMON BUENO Y JOSE TRIANA,1
GIRARDOT,I.E. NUEVO HORIZONTE,24
GIRARDOT,LICEO LOS ANDES,8
GIRARDOT,SEDE FRANCISCO J DE CALDAS,13
GIRARDOT,CTRO EDU ANTONIO NARIÑO,13
GIRARDOT,COL MAYOR MARTHA CATALINA,20
GIRARDOT,JARDIN INFANTIL CHIQUITOS,2
GIRARDOT,JARDIN INFANTIL CHEPITA MENDEZ,3
GIRARDOT,IET FRANCISCO MANZANERA HENRIQUEZ,5
GIRARDOT,COLISEO CENTENARIO,3
GIRARDOT,ESC. NORMAL SUPERIOR MARIA AUX,19
GIRARDOT,COLEGIO ATANASIO GIRARDOT,18
GIRARDOT,COLISEO BARRIO SAN JORGE,15
GIRARDOT,COLISEO BARRIO KENNEDY,11
GIRARDOT,IE POLICARPA SALAVARRIETA,19
GIRARDOT,SENA,4
GIRARDOT,IE SEDE INTEGRADORA,2
GIRARDOT,FUNDACION CAMPESTRE EL PEÑON,2
GIRARDOT,COLEGIO ESPIRITU SANTO,5
GIRARDOT,COLISEO DEFERIAS Y EXPOSICION,8
GIRARDOT,PENITENCIARIA NACIONAL,1
GIRARDOT,BARZALOSA Y PIAMONTE,10
GIRARDOT,SAN LORENZO,1
GUACHETA,PUESTO CABECERA MUNICIPAL,29
GUACHETA,MONROY,1
GUADUAS,IED MIGUEL SAMPER AGUDELO,36
GUADUAS,IED MIGUEL SAMPER SEDE BENJAMIN HERRERA,18
GUADUAS,JARDIN INFANTIL MI PEQUEÑO MUNDO-MIMOS1,2
GUADUAS,IED MIGUEL SAMPER AGUDELO SD URB. FJM,2
GUADUAS,PENIT. DE MEDIANA SEG. LA ESPERANZA,1
GUADUAS,LA PAZ,3
GUADUAS,CUATRO ESQUINAS,1
GUADUAS,GUADUERO,1
GUADUAS,SEDE RURAL CEDRALES,1
GUADUAS,IED PUERTO BOGOTA SEDE PRINCIPAL,8
GUADUAS,VEREDA TAUCHIRAL ESCUELA SEDE SAN GIL,1
GUADUAS,EL ESCRITORIO,1
GUADUAS,MALAMBO,1
GUADUAS,ESCUELA RURAL MADRIGAL Y CHAPAIMA,1
GUASCA,PUESTO CABECERA MUNICIPAL,37
GUASCA,INSTITUCION EDUCATIVA EL CARMEN,1
GUATAQUI,PUESTO CABECERA MUNICIPAL,9
GUATAVITA,PUESTO CABECERA MUNICIPAL,17
GUAYABAL DE SIQUIMA,PUESTO CABECERA MUNICIPAL,14
GUAYABAL DE SIQUIMA,SALON COMUNAL EL TRIGO,1
GUAYABAL DE SIQUIMA,ESCUELA RURAL LA CONCORDIA,1
GUAYABETAL,PUESTO CABECERA MUNICIPAL,14
GUAYABETAL,TUNQUE DEL NARANJAL (TUNQUE),1
GUTIERREZ,PUESTO CABECERA MUNICIPAL,9
GRANADA,PUESTO CABECERA MUNICIPAL,21
JERUSALEN,PUESTO CABECERA MUNICIPAL,9
JUNIN,PUESTO CABECERA MUNICIPAL,12
JUNIN,CLARAVAL,1
JUNIN,CHUSCALES,2
JUNIN,EL SALITRICO (SUEVA),3
LA CALERA,POLIDEPORTIVO  LA PORTADA,17
LA CALERA,SALON COMUNAL MARQUEZ,3
LA CALERA,ESCUELA JUAN XXIII,41
LA CALERA,ESCUELA EL SALITRE,5
LA CALERA,POLIDEPORTIVO PASEO REAL,7
LA CALERA,CASA DE LA CULTURA,3
LA CALERA,MUNDO NUEVO,2
LA CALERA,TREINTA Y SEIS,2
LA MESA,POLIDEP. LUIS CARLOS GALAN SARMIENTO,16
LA MESA,I.E. D. FRANCISCO JULIAN OLAYA SEDE A,16
LA MESA,SABIO MUTIS SEDE ANTIGUA,20
LA MESA,I.E. D. FRANCISCO JULIAN OLAYA SEDE C,18
LA MESA,CARCEL,1
LA MESA,LA ESPERANZA,5
LA MESA,SAN JOAQUIN,7
LA MESA,SAN JAVIER,4
LA PALMA,ESC. NORMAL SUPERIOR DIVINA PROVIDENCIA,22
LA PALMA,MINIPI QUIJANO,2
LA PALMA,ESCUELA RURAL HINCHE BAJO,1
LA PALMA,MURCA,2
LA PALMA,LA HOYA DE TUDELA,1
LA PEÑA,PUESTO CABECERA MUNICIPAL,18
LA PEÑA,CASA DE LA MUJER,1
LA PEÑA,COLEGIO POLIDEPORTIVO AGUA BLANCA,1
LA VEGA,PUESTO CABECERA MUNICIPAL,42
LA VEGA,EL VINO,2
LENGUAZAQUE,PUESTO CABECERA MUNICIPAL,22
LENGUAZAQUE,IE DEPARTAMENTAL RURAL SIMON BOLIVAR,2
MACHETA,PUESTO CABECERA MUNICIPAL,20
MADRID,COLISEO  CUBIERTO MUNICIPAL,22
MADRID,COLEGIO SAN PEDRO,18
MADRID,SALON  COMUNAL  ALCAPARROS,9
MADRID,COLEGIO LA MAGNOLIA,8
MADRID,LICEO HACIENDA CASABLANCA,19
MADRID,COLEGIO TIBAITATA,22
MADRID,COLEGIO PEDAGOGICO INGLES,10
MADRID,JARDIN INFANTIL CAMPO DE ILUSIONES,3
MADRID,PARQUE DE LAS FLORES,5
MADRID,CONCENTRACION URBANA EL CORTIJO,11
MADRID,COLEGIO GABRIEL ECHAVARRIA,13
MADRID,COLEGIO DEPTAL SERREZUELA,21
MADRID,COLEGIO TECNOLOGICO DE MADRID,13
MADRID,I.E.NUESTA SRA DEL LORETO,12
MADRID,COLEGIO MARIA TERESA ORTIZ,19
MADRID,COLEGIO  SAN  JOSE,15
MADRID,BLOQUE 2 - COLEGIO TECNOLOGICO,15
MADRID,COLEGIO SANTO TOMAS,11
MADRID,COLEGIO LA PROSPERIDAD,14
MADRID,CONCENTRACION URBANA ANTONIO NARIÑO,3
MADRID,IE DEPTAL SAN PATRICIO PUENTE DE  PIEDRA,10
MANTA,PUESTO CABECERA MUNICIPAL,13
MEDINA,PUESTO CABECERA MUNICIPAL,16
MEDINA,EL ARENAL,1
MEDINA,LA ESMERALDA,1
MEDINA,GAZATAVENA,1
MEDINA,SAN MARCOS,1
MEDINA,PERIQUITO,1
MEDINA,LOS ALPES,1
MEDINA,LA MESA DE LOS REYES,1
MEDINA,SAN FRANCISCO DE GAZADUJE,1
MEDINA,SAN PEDRO DE GUAJARAY,1
MEDINA,SANTA TERESITA,1
MOSQUERA,NUEVO COLISEO MUNICIPAL,23
MOSQUERA,IE JUAN LUIS LONDOÑO,20
MOSQUERA,COLEGIO LA PAZ,26
MOSQUERA,ESCUELA EL DIAMANTE,8
MOSQUERA,COL MAYOR DE MOSQUERA,13
MOSQUERA,IE LA AMISTAD,11
MOSQUERA,ESCUELA LOS PUENTES,1
MOSQUERA,IE LA MERCED,12
MOSQUERA,IE ANTONIO NARIÑO,4
MOSQUERA,SECTOR NOVATERRA,9
MOSQUERA,COLEGIO ROBERTO VELANDIA,29
MOSQUERA,IE LA ARMONIA,27
MOSQUERA,JARDIN INF VILLA MARCELA,27
MOSQUERA,EL TREBOL COL COMPARTIR,30
MOSQUERA,COL LA FRATERNIDAD,23
MOSQUERA,IE FRANCISCO DE PAULA SANTANDER,6
MOSQUERA,IE NUEVO MILENIO,10
MOSQUERA,CC ECOPLAZA,13
NARIÑO,PUESTO CABECERA MUNICIPAL,9
NEMOCON,POLIDEPORTIVO FRAY IGNACIO MARIÑO,21
NEMOCON,IE DEPARTAMENTAL ALFONSO LOPEZ PUMAREJO,8
NEMOCON,VEREDA PATIO BONITO,6
NILO,PUESTO CABECERA MUNICIPAL,14
NILO,IED PUEBLO NUEVO,3
NILO,IED LA ESMERALDA,3
NIMAIMA,PUESTO CABECERA MUNICIPAL,7
NIMAIMA,TOBIA,4
NIMAIMA,EL CERRO,1
NOCAIMA,PUESTO CABECERA MUNICIPAL,17
PACHO,COLISEO CUBIERTO LORENZO DE TERRONES,23
PACHO,I.E.D. AQUILEO PARRA,16
PACHO,IED ANA FRANCISCA LARA SD ANTONIO NARIÑO,3
PACHO,I.E. D. ANA FRANCISCA LARA SD SAN JOSE,17
PACHO,I.E.D. ANA FRANCISCA LARA SEDE BOLIVAR,8
PACHO,IED INST TEC AGRIC SD CNIA ALBERTO NIETO,5
PACHO,INSTITUCION EDUCATIVA PASUNCHA,3
PAIME,PUESTO CABECERA MUNICIPAL,8
PAIME,CUATRO CAMINOS,2
PAIME,EL PLOMO (EL PARAISO),1
PAIME,TUDELA,4
PAIME,VENECIA,1
PANDI,PUESTO CABECERA MUNICIPAL,14
PARATEBUENO (LA NAGUAYA),PUESTO CABECERA MUNICIPAL,16
PARATEBUENO (LA NAGUAYA),EL ENGAÑO,1
PARATEBUENO (LA NAGUAYA),GUAICARAMO,1
PARATEBUENO (LA NAGUAYA),MAYA,4
PARATEBUENO (LA NAGUAYA),SANTA CECILIA,2
PARATEBUENO (LA NAGUAYA),VILLA PACHELLY,1
PARATEBUENO (LA NAGUAYA),CENTRO POBLADO JAPON,1
PASCA,PUESTO CABECERA MUNICIPAL,26
PUERTO SALGAR,COLEGIO TECNICO DEPARTAMENTAL MIXTO,25
PUERTO SALGAR,IED POLICARPA SALAVARRIETA,12
PUERTO SALGAR,COLORADOS,1
PUERTO SALGAR,LA REINES,1
PUERTO SALGAR,PUERTO LIBRE,3
PULI,PUESTO CABECERA MUNICIPAL,8
PULI,VALPARAISO,1
PULI,PALESTINA,2
PULI,ESCUELA RURAL CABRERA,1
QUEBRADANEGRA,PUESTO CABECERA MUNICIPAL,5
QUEBRADANEGRA,LA MAGDALENA,6
QUEBRADANEGRA,SAN CARLOS,2
QUEBRADANEGRA,TOBIA,1
QUETAME,PUESTO CABECERA MUNICIPAL,10
QUETAME,PUENTE QUETAME - PUENTE CLAVIJO,8
QUIPILE,PUESTO CABECERA MUNICIPAL,10
QUIPILE,LA SIERRA,3
QUIPILE,LA VIRGEN,3
QUIPILE,LA BOTICA,3
QUIPILE,SANTA MARTA,2
APULO,POLIDEPORTIVO MUNICIPAL APULO,19
APULO,IED ANTONIO NARIÑO,4
RICAURTE,MEGA COLEGIO ANTONIO RICAURTE,24
RICAURTE,UNIDAD DEPORTIVA,15
RICAURTE,CIC SACUDETE VEREDA LLANO DEL POZO,1
SAN ANTONIO DEL TEQUENDAMA,PUESTO CABECERA MUNICIPAL,16
SAN ANTONIO DEL TEQUENDAMA,SANTANDERCITO,12
SAN BERNARDO,PUESTO CABECERA MUNICIPAL,23
SAN BERNARDO,CASA DE GOBIERNO PORTONES,2
SAN CAYETANO,PUESTO CABECERA MUNICIPAL,7
SAN CAYETANO,CAMANCHA,1
SAN CAYETANO,CUIBUCO,2
SAN CAYETANO,LAGUNA VERDE,1
SAN CAYETANO,LAS MERCEDES,2
SAN CAYETANO,PINIPAY,2
SAN CAYETANO,REMANSO,1
SAN CAYETANO,EL ALBERGUE,1
SAN FRANCISCO,PUESTO CABECERA MUNICIPAL,28
SAN FRANCISCO,ESCUELA RURAL EL BOSQUE,1
SAN FRANCISCO,ESCUELA RURAL SAN LUIS,1
SAN FRANCISCO,ESCUELA RURAL SAN MIGUEL,1
SAN FRANCISCO,ESCUELA RURAL SAN ANTONIO,1
SAN JUAN DE RIOSECO,CIC ANTIGUO POLIDEPORTIVO,17
SAN JUAN DE RIOSECO,IED SAN JUAN DE RIOSECO ESCUELA ANEXA,6
SAN JUAN DE RIOSECO,IERD DIEGO URIBE VARGAS DE CAMBAO,4
SAN JUAN DE RIOSECO,SAN NICOLAS,2
SAN JUAN DE RIOSECO,I.E.D RURAL LAGUNITAS,1
SASAIMA,AUDITORIO MUNICIPAL,20
SASAIMA,IED NUESTRA SEÑORA DE FATIMA,7
SASAIMA,LA VICTORIA,3
SESQUILE,COLISEO MUNICIPAL,24
SESQUILE,COMPLEJO DEPORTIVO,6
SIBATE,IED GRAL SANTANDER SEDE BTO,23
SIBATE,IED PABLO NERUDA,14
SIBATE,COLISEO XIUA,7
SIBATE,POLIDEPORTIVO SANTA ISABEL,5
SIBATE,C.I.C BALCONES DE SAN JOSE,18
SIBATE,POLIDEPORTIVO SAN RAFAEL,15
SIBATE,IED GRAL SANTANDER SEDE PRIMARIA,7
SILVANIA,COLISEO MUNICIPAL,30
SILVANIA,COLEGIO NUEVO SANTA INES,19
SILVANIA,AGUA BONITA,4
SILVANIA,SUBIA,9
SIMIJACA,COLEGIO AGUSTIN PARRA SEDE PRIMARIA,16
SIMIJACA,COLEGIO AGUSTIN PARRA SEDE BACHILLERATO,16
SIMIJACA,EL SALITRE,1
SOACHA,I. E. SANTA ANA - ANTONIO NARIÑO,24
SOACHA,I.E. COMPARTIR,33
SOACHA,I.E. CIUDAD LATINA,30
SOACHA,IE. NUEVO COMPARTIR,14
SOACHA,CONCENTRACION ESCOLAR SAN NICOLAS,16
SOACHA,I.E. COMPARTIR PRIMARIA,30
SOACHA,IE JUAN PABLO SEGUNDO SOACHA,15
SOACHA,COLEGIO COLSUBSIDIO - MAIPORE,7
SOACHA,I.E. PAZ Y ESPERANZA,7
SOACHA,SALON COMUNAL VILLA ITALIA,3
SOACHA,COLEGIO MILITAR LICEO SOCIAL COMPARTIR,16
SOACHA,I.E. GENERAL SANTANDER,36
SOACHA,IE GENERAL SANTANDER SD MI TIERNA EDAD,19
SOACHA,I.E. INTEGRADO DE SOACHA,33
SOACHA,COLISEO GENERAL SANTANDER,21
SOACHA,CONCENTRACION CAMILO TORRES,18
SOACHA,I E GENERAL SANTANDER SEDE LA VEREDITA,7
SOACHA,SALON COMUNAL CIUDAD SATELITE,13
SOACHA,UNIVER. DE CUNDINAMARCA EXTENSION SOACHA,25
SOACHA,CENTRO DE DESARROLLO INFANTIL COMPENSAR,7
SOACHA,I.E. VIDA NUEVA,22
SOACHA,CDI JARDIN SOCIAL SOL Y LUNA,9
SOACHA,IE LUIS HENRIQUEZ,6
SOACHA,COLEGIO COOPERATIVO EUGENIO DIAZ CASTRO,6
SOACHA,CENTRO DEPORTIVO PARQUE DE LOS LOCOS,25
SOACHA,I.E. LA DESPENSA,10
SOACHA,I.E. MANUELA BELTRAN,8
SOACHA,I.E. LEON XIII,27
SOACHA,CENTRO COMERCIAL GRAN PLAZA,31
SOACHA,COLISEO LEON XIII,25
SOACHA,I.E. LA DESPENSA - CIUDAD VERDE,17
SOACHA,I.E. LEON XIII - CHILOE,33
SOACHA,I.E. LA DESPENSA - MARCO FIDEL SUAREZ,3
SOACHA,I.E. SOACHA AVANZA LA UNIDAD,28
SOACHA,COLEGIO MINUTO DE DIOS CIUDAD VERDE,26
SOACHA,IE BENEDICTO XVI,2
SOACHA,CENTRO COMERCIAL MERCURIO,23
SOACHA,I.E. LUIS CARLOS GALAN,9
SOACHA,I.E. CIUDADELA SUCRE,24
SOACHA,I.E. LA ISLA,10
SOACHA,I E JULIO CESAR TURBAY AYALA,20
SOACHA,I. E. GABRIEL GARCIA MARQUEZ,4
SOACHA,IE LUIS C. GALAN-SD VILLAS DE CASALOMA,3
SOACHA,BIBLIOTECA MUNICIPAL LA ISLA,4
SOACHA,IE BUENOS AIRES SEDE A,4
SOACHA,LICEO NUEVA VIDA,1
SOACHA,CTRO REG. DE ATENCION A VICTIMAS CRAV,1
SOACHA,CENTRO COMERCIAL VENTURA TERREROS,29
SOACHA,I.E. EL BOSQUE,28
SOACHA,I.E. SAN MATEO SEDE A,30
SOACHA,I.E. SAN MATEO SEDE B,21
SOACHA,I.E. LICEO MAYOR DE SOACHA,25
SOACHA,CTRO DE ATENCION A PERSONAS CON DISCAP.,1
SOACHA,CENTRO COMERCIAL UNISUR,8
SOACHA,I.E. LAS VILLAS- SEDE BARON DEL SOL,28
SOACHA,I.E. LAS VILLAS - SEDE LIBERTADORES,6
SOACHA,I.E. SOL NACIENTE,24
SOACHA,I.E. SAN MATEO - MARISCAL SUCRE,14
SOACHA,I E EDUARDO SANTOS SEDE PANAMERICANA,16
SOACHA,I.E. SOACHA PARA VIVIR MEJOR,5
SOACHA,SALON COMUNAL ALTOS DE LA FLORIDA,3
SOACHA,LICEO CRISTIANO VIDA NUEVA,5
SOACHA,IE EDUARDO SANTOS,5
SOACHA,IE RICAURTE SEDE PORVENIR,1
SOACHA,IE RICAURTE SEDE ESPAÑA,10
SOACHA,COLEGIO BOLIVAR PRIMARIA,11
SOACHA,I. E. EUGENIO DIAZ CASTRO SEDE CHACUA,2
SOACHA,I. E. EUGENIO DIAZ CASTRO SAN JORGE,3
SOACHA,SALON COMUNAL VEREDA FUSUNGA,1
SOACHA,I. E. EUGENIO DIAZ CASTRO SEDE PRIMARIA,4
SOACHA,SALON COMUNAL SAN FRANCISCO,1
SOPO,COLISEO MUNICIPAL,24
SOPO,C ACONDICIONAMIENTO Y PRE FISICA CAPF II,26
SOPO,ESCENARIO COMUN. INTEGRAL EL CHUSCAL,6
SOPO,COLEGIO COOPERATIVO SOPO,2
SOPO,BRICEÑO,6
SOPO,LA VIOLETA,1
SUBACHOQUE,IED RICARDO GONZALEZ SEDE A,25
SUBACHOQUE,COLISEO MUNICIPAL SUBACHOQUE,12
SUBACHOQUE,LA PRADERA,3
SUBACHOQUE,EL GUAMAL,1
SUESCA,PUESTO CABECERA MUNICIPAL,33
SUESCA,HATO GRANDE,2
SUESCA,SANTA ROSITA,2
SUESCA,IE DPTAL CACICAZGO,1
SUPATA,PUESTO CABECERA MUNICIPAL,15
SUSA,PUESTO CABECERA MUNICIPAL,17
SUTATAUSA,PUESTO CABECERA MUNICIPAL,12
SUTATAUSA,LAS PEÑAS,2
TABIO,POLIDEPORTIVO MUNICIPAL - TABIO,25
TABIO,CASA DE LA CULTURA,16
TABIO,COLEGIO GIMNASIO MODERNO SANTA BARBARA,14
TABIO,IED JOSE DE SAN MARTIN,2
TABIO,IEDR DIEGO GOMEZ DE MENA,1
TAUSA,POLIDEPORTIVO MUNICIPAL,15
TAUSA,IEDIT-IE DPTAL INTEGRADA DE TAUSA,4
TAUSA,EL SALITRE,1
TAUSA,PARAMO ALTO,1
TENA,PUESTO CABECERA MUNICIPAL,14
TENA,PUESTO INSPECCION LA GRAN VIA,10
TENJO,POLIDEPORTIVO MUNICIPAL,27
TENJO,IED GENERAL SANTANDER,20
TENJO,SALON MULTIFUNCIONAL CASA DE LA MUJER,7
TENJO,LA PUNTA,4
TIBACUY,PUESTO CABECERA MUNICIPAL,7
TIBACUY,CUMACA,5
TIBACUY,SALON COMUNAL BATEAS,3
TIBIRITA,PUESTO CABECERA MUNICIPAL,10
TOCAIMA,POLIDEPORTIVO PEPE ZABALA,21
TOCAIMA,CENTRO DE INTEGRACION CIUDADANA,19
TOCAIMA,PUBENZA,1
TOCANCIPA,COLEGIO SAN LUIS GONZAGA,24
TOCANCIPA,INS. EDUCATIVA LA FUENTE,13
TOCANCIPA,INST EDU DEPARTAMENTAL TECNICO COMERCIAL,16
TOCANCIPA,COLISEO MUNICIPAL DE TOCANCIPA,7
TOCANCIPA,I. E. DPTAL TECNICO INDUSTRIAL,19
TOCANCIPA,INSTITUCION EDUCATIVA CANAVITA,12
TOCANCIPA,CENTRO DE INTEGRACION CIUDADANA CIC,22
TOCANCIPA,SALON COMUNAL DE CANAVITA,5
TOCANCIPA,SALON COMUNAL TORRES DE SAN JUAN,4
TOCANCIPA,ESCUELA RURAL LA ESMERALDA,3
TOCANCIPA,SALON COMUNAL LA ESMERALDA,1
TOPAIPI,PUESTO CABECERA MUNICIPAL,9
TOPAIPI,SAN ANTONIO DE AGUILERA,3
TOPAIPI,EL NARANJAL,2
UBALA,PUESTO CABECERA MUNICIPAL,17
UBALA,VEREDA SANTA BARBARA,1
UBALA,LA PLAYA,1
UBALA,LAGUNA AZUL,2
UBALA,VEREDA SAN PEDRO,1
UBALA,MAMBITA,3
UBALA,VEREDA SAN JUAN,1
UBALA,PEÑAS BLANCAS,1
UBALA,VEREDA RIO NEGRO,1
UBALA,SAN PEDRO DE JAGUA,2
UBALA,LA MESA,1
UBALA,SANTA ROSA,2
UBALA,INSTITUCION EDUCATIVA SOYA,1
UBALA,INSTITUCION EDUCATIVA LAS MARGARITAS,1
UBAQUE,PUESTO CABECERA MUNICIPAL,19
UBAQUE,PUESTO VEREDA SABANILLA,1
UBATE,UNIVERSIDAD CUNDINAMARCA,23
UBATE,CENTRO COMERCIAL LA SEGUNDA,13
UBATE,MEGA COLEGIO BARRIO SAN JOSE,8
UBATE,UNIDAD BASICA,14
UBATE,ESCUELA NORMAL SUPERIOR,2
UBATE,INSTITUTO BOLIVAR,21
UBATE,COLISEO MUNICIPAL,27
UBATE,COLEGIO SANTA MARIA,2
UBATE,CARCEL,1
UBATE,VIENTO LIBRE,2
UBATE,BRUSELAS,1
UBATE,VOLCAN DOS,1
UBATE,ESCUELA RURAL TAUSAVITA,1
UBATE,GUATANCUY,3
UNE,COLISEO POLIDEPORTIVO GUSTAVO MOYA ANGEL,21
UNE,ESCUELA PEDRO ELISEO CRUZ,1
UNE,INSPECCION DE POLICIA EL RAMAL,1
UTICA,PUESTO CABECERA MUNICIPAL,16
VENECIA,COLISEO DE DEPORTES,11
VENECIA,ESCUELA SAN ANTONIO,1
VENECIA,APOSENTOS,1
VENECIA,ESCUELA LAS BRISAS,1
VERGARA,PUESTO CABECERA MUNICIPAL,16
VERGARA,CERINZA,1
VERGARA,CORCEGA,1
VERGARA,CHONTEGRANDE,2
VERGARA,GUACAMAYAS,1
VERGARA,LLANO GRANDE,2
VERGARA,VILLA OLARTE (FLANDES),1
VIANI,PUESTO CABECERA MUNICIPAL,14
VILLAGOMEZ,PUESTO CABECERA MUNICIPAL,7
VILLAGOMEZ,CERRO AZUL,1
VILLAPINZON,PLAZA DE MERCADO,34
VILLAPINZON,COL. MPAL FRANCISCO DE VARGAS FIGUEROA,11
VILLETA,ESCUELA LA VALENCIA,19
VILLETA,SENA,18
VILLETA,CONC. POLICARPA SALAVARRIETA,19
VILLETA,ESCUELA CARLOS LLERAS,14
VILLETA,IED PROMOCION SOCIAL,4
VILLETA,CARCEL MUNICIPAL,1
VILLETA,IED COLEGIO CUNE,1
VILLETA,BAGAZAL,3
VILLETA,CHAPAIMA,1
VILLETA,ILO GRANDE,1
VIOTA,CENTRO POLIDEPORTIVO MUNICIPAL,17
VIOTA,ESCUELA MARIA INMACULADA,12
VIOTA,SAN GABRIEL,4
VIOTA,BRASIL,3
VIOTA,EL PIÑAL,2
VIOTA,IED BAJO PALMAR,1
YACOPI,PUESTO CABECERA MUNICIPAL,18
YACOPI,ALSACIA,2
YACOPI,ALTO DE CAÑAS,1
YACOPI,APOSENTOS,1
YACOPI,EL CHAPON (LAS LOMAS),1
YACOPI,GUADUALITO,2
YACOPI,CABO VERDE,1
YACOPI,ESCUELA GUAYABALES,2
YACOPI,IBAMA,2
YACOPI,LLANO MATEO,3
YACOPI,PATEVACA,2
YACOPI,PUEBLO NUEVO,1
YACOPI,TERAN,2
YACOPI,VEREDA EL CASTILLO,1
ZIPACON,PUESTO CABECERA MUNICIPAL,10
ZIPACON,EL OCASO,3
ZIPAQUIRA,IEM CUNDINAMARCA,33
ZIPAQUIRA,COLEGIO RAFAEL POMBO,12
ZIPAQUIRA,ESCUELA QUEVEDO Z,44
ZIPAQUIRA,SEDE EDU SIMON BOLIVAR,32
ZIPAQUIRA,IEM SAN JUAN BAUTISTA DE SALLE SD PRIMAR,13
ZIPAQUIRA,SALON COMUNAL SANJUANITO,9
ZIPAQUIRA,IEM TEC LUIS ORJUELA SEDE MARISCAL SUCRE,3
ZIPAQUIRA,ESCUELA FRANCISCO DE PAULA SANTANDER,1
ZIPAQUIRA,IEM GUILLERMO QUEVEDO Z SD LA 14,3
ZIPAQUIRA,CIC DE PRADOS DEL MIRADOR,3
ZIPAQUIRA,COLEGIO LICEO INTEGRADO,37
ZIPAQUIRA,INST.EDUC.SANTIAGO PEREZ,38
ZIPAQUIRA,GABRIELA MISTRAL SEDE NUEVA,25
ZIPAQUIRA,CAMI PAUZ,7
ZIPAQUIRA,COLEGIO DE LA PRESENTACION,14
ZIPAQUIRA,COLISEO ARENA DE SAL,12
ZIPAQUIRA,CIC DE BARANDILLAS,2
ZIPAQUIRA,I.E. DPTAL TECNICO INDUSTRIAL,21
ZIPAQUIRA,CORREGIMIENTO 1 ESC SAN ISIDRO,4
ZIPAQUIRA,CORREGIMIENTO 2 (ESC BARANDILLAS),18
ZIPAQUIRA,CORREGIMIENTO 3 (ESC SAN JORGE),4
ZIPAQUIRA,CORREGIMIENTO 2 ESCUELA SAN MIGUEL,1`;

const lines = text.split('\n').map(l => l.trim()).filter(l => l);
const data = [];
for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(',');
    if (parts.length >= 3) {
        data.push({
            municipio: parts[0].trim(),
            punto: parts[1].trim(),
            mesas: parseInt(parts[2].trim()) || 0
        });
    }
}
fs.writeFileSync('c:/Users/Usuario/OneDrive/Escritorio/Pagina web/testigos-pl/lib/mesas-data.json', JSON.stringify(data, null, 2));
console.log('Success, lines extracted: ' + data.length);
